### ISSUE TITLE
Panel on Responsible AI: Tackling AI's Environmental Challenge

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#46]
Review options to host an AI panel discussion.

- [x] Elise to provide a Thoughtwork point of contact

**Comment by adamj89** [comment]
For online events we have a Streamyard license, I would be happy to produce an event which could be shared via the Meetup networks & broadcast on YouTube & LinkedIn.

**Comment by NAMRATA-WOKE** [comment]
AI Panel Speaker Nominations from SC:

Jesse McCrosky - Thoughtworks
Navveen Balani - Accenture
Chris McClean - Avanade 

Patryk from Microsoft advised we get someone from Meta b/c of a [recent paper ](https://scontent.frns1-1.fna.fbcdn.net/v/t39.2365-6/10000000_662098952474184_2584067087619170692_n.pdf?_nc_cat=105&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=qhK-ahCbkBMAX9roDRC&_nc_ht=scontent.frns1-1.fna&oh=00_AfCCy5OutKsJrIlIOFrtbQ00OqX2DO8KsjysV-XOE4yT_w&oe=64BE66FF)-- @jawache, what are your thoughts on engaging Meta?

**Comment by adamj89** [comment]
@NAMRATA-WOKE I think Patrick also said he would seek someone inside MSFT. Not sure if thats in addition or alternative to Meta.

**Comment by NAMRATA-WOKE** [comment]
@jawache are you comfortable with the people shortlisted above? I have drafted an email for them which I am happy to send out on behalf of GSF! 

Dear [AI Expert's Name],

On behalf of the Green Software Foundation, I'd like to invite you to participate as a panelist in our upcoming virtual event on Responsible AI. Your expertise and experience make you a perfect fit for this critical discussion.

While ethical considerations and social impact are critical dimensions to the broader responsible AI conversation, we are eager to delve deeper into the environmental impact considerations of AI, primarily the challenges and opportunities to reduce carbon emissions and energy consumption for AI, including generative AI to be greener and more carbon-aware.

### Event Details: 

**Date:** Tuesday, October 3rd, or Thursday, October 5th, depending on speaker availability. 

**Time:** 9:00 am EST / 2:00 pm BST / 9:00 pm SGT 

**Duration:** 60 minutes 

**Please confirm your availability and interest by September 15th.** 

Thank you for considering our invitation! We hope you join this discussion.

Best,
Namrata

**Comment by jawache** [comment]
Sounds good to me!

**Comment by NAMRATA-WOKE** [comment]
@jawache do you think we could get Sasha Luccioni from Hugging Face as a panelist? Do we have any connections?

**Comment by NAMRATA-WOKE** [comment]
Outreach:

- [ ] Sasha Luccioni - Hugging Face
- [ ] Jesse McCrosky - Thoughtworks
- [ ] Navveen Balani - Accenture
- [ ] Chris McClean - Avanade
- [ ] Abhishek Gupta - BCG X

**Comment by NAMRATA-WOKE** [comment]
Abhishek Gupta is not available. Navveen has confirmed. BCG X in the process of nominating other candidates for us to consider.

**Comment by adamj89** [comment]
@NAMRATA-WOKE timings if we delayed by 1 hours:



![Image](https://github.com/Green-Software-Foundation/policy-wg/assets/20337337/70055b8b-7814-4fbe-93c9-7f1eef042c4e)

**Comment by NAMRATA-WOKE** [comment]
@adamj89 can you create the Meetup page for this event tomorrow? We aren't kicking off main promotion but I thought it would be nice to share the link with our members ahead of time. Let me know if it's possible. I am happy to do it as well - just need access!

**Comment by NAMRATA-WOKE** [comment]
![Image](https://github.com/Green-Software-Foundation/policy-wg/assets/114516498/420893b5-ecb1-4067-ac87-767eae9fba99)

For Meetup image.

**Comment by adamj89** [comment]
Hi @NAMRATA-WOKE 

Of course! Could we remove Streamyard from the graphic? That's of no relevance to our audience and will cause confusion. "Live online event" would work well.

**Comment by adamj89** [comment]
Also time zones are slightly out

Should be 
9am EDT | 2pm BST | 6.30pm IST

**Comment by NAMRATA-WOKE** [comment]
@adamj89  Silly me - I sent the wrong one. Need the initial image to be a bit sparse on the details since we're still in the process of finalizing speakers - the date/time will reflect confirmed panelists.

Could we use this one temporarily? I'll make sure the final image for marketing reflects your comments above!

![Image](https://github.com/Green-Software-Foundation/policy-wg/assets/114516498/60dc426f-e99a-4cc8-9241-03d06186e474)

**Comment by adamj89** [comment]
@NAMRATA-WOKE that one is perfect!

**Comment by adamj89** [comment]
@NAMRATA-WOKE here is the global link https://www.meetup.com/gsf-global/events/295596991/

The event is also in every owned GSF group. It has not been ‘announced’ but it will be visible to anyone visiting the groups.

**Comment by NAMRATA-WOKE** [comment]
You're the best, thanks! @adamj89

**Comment by NAMRATA-WOKE** [comment]
@NAMRATA-WOKE reached out to Dr. Ebtesam Almazrouei, Executive Director, Acting Chief AI Researcher and Co Founder - Artificial Intelligence Cross-Center, to see if she would be interested in participating. Based in the UAE. Waiting to hear back.

**Comment by adamj89** [comment]
@NAMRATA-WOKE have you spoken to Ben Logan @ UBS about this event?

**Comment by adamj89** [comment]
@mrchrisadams tagging you here for review.

**Comment by seanmcilroy29** [comment]
https://github.com/Green-Software-Foundation/standards-wg/discussions/71

**Comment by NAMRATA-WOKE** [comment]
@adamj89 is there a specific reason you want me to connect specifically with Ben Logan about the panel? I haven't reached out to Elif. Will explore. I reached out to Will last week (Friday) asking for recommendations. Haven't heard back so will follow-up tomorrow.

**Comment by NAMRATA-WOKE** [comment]
Drafted e-comms reminders for the panel event: https://docs.google.com/document/d/10Fn7TxjvH_Lgmplc708O2yPD4p_tbeU80jkLnVwB7ek/edit

**Comment by adamj89** [comment]
Looks great to me, I’m not sure how “rich” the email can be on meetup so will have to check if we can embed the images

**Comment by NAMRATA-WOKE** [comment]
My introduction:

Today, we're all here to delve into the intricate relationship between responsible AI and environmental sustainability. We wholeheartedly acknowledge that AI possesses the transformative potential to tackle some of our planet's most pressing global challenges, yet it also carries an environmental toll that can be detrimental to the health of our planet and societies.

Our mission is to lead AI down a greener path where sustainability and innovation are complementary. Before we dive into this discussion, let's take a sneak peek at the pivotal themes our panelists will unravel today:

1. **The current state of green software and the road ahead:** Together, we'll explore the current landscape of eco-conscious technology and the exciting prospects that lie on the horizon.
2. **Practices and principles for eco-friendly AI design and development:** We'll shine a spotlight on established environmentally-centric strategies and approaches that are paving the way for a sustainable AI ecosystem.
3. **Tools and methods for measuring AI's carbon footprint:** Embark with us on a journey to discover how we can accurately gauge AI's environmental impact and, more importantly, take proactive steps to reduce it.
4. **The pivotal role of policy-makers, AI Sustainability Officers, and more:** We'll delve into the multifaceted roles played by various stakeholders in shaping the future of sustainable AI.
5. **Empowering individuals and sustainability groups to drive change:** Learn about actionable ways that individuals and groups can actively contribute to making AI greener and more sustainable.

To guide us through these themes, we're happy to have experts in their field, working at the intersection of AI and Sustainability, who'll bring a wealth of knowledge to today's discussion. 

To moderate the discussion, we have Dawn Nafus, Anthropologist and Senior Research Scientist at Intel Labs with us. Dawn is an expert in health and environmental sensing, data, and digital research methods. 

On the panel, we have: 

Chris McClean, Global Lead for Digital Ethics at Avanade. Chris drives the company’s internal responsible tech and responsible AI efforts, and he leads the company’s digital ethics advisory practice. 

Navveen Balani, Chief Technologist at the Technology Sustainability Innovation Group at Accenture. Navveen possesses extensive expertise across multiple domains, including Multi-Cloud Strategy, Scalable Deployments, Technology Sustainability, AI, Generative AI, Big Data, and the Internet of Things. His latest book, "Unlocking Generative AI with Prompt Engineering," explores generative AI and prompt engineering techniques, providing practical insights for professionals and enthusiasts. 

Dr. Elif Kiesow Cortez, Director of Quantum & AI at Ethiqual and Research Fellow on Tech Ethics & Governance at Stanford Law School. Elif has been appointed as an advisory board member for projects of the UNFCCC, European Research Council, IAPP and she currently participates in developing privacy enhancing technology standards for a project of the IEEE SA. She was a member of the UN IGF Policy Network on Environment.

Welcome everyone! For those joining us, we invite you to actively participate by asking questions, sharing your insights, and recounting your experiences. We're actively monitoring GSF Discussions (link in chat) during this event to capture your comments and questions.

So, let's get started. Dawn, the mic is yours!

**Comment by NAMRATA-WOKE** [comment]
@NAMRATA-WOKE to include:

- Title slide 
- Code of conduct
- How to engage during the event
- Intro to GSF and green software 
- How to stay involved with the GSF (newsletter, meetups, training, decarb, open-source projects)

**Comment by NAMRATA-WOKE** [comment]
My introduction:

Welcome everyone! My name is Namrata and I am the Director of Communications and Member Relations at the Green Software Foundation. I'm so excited for this next hour. For those of you who are joining a GSF event for the first time, thank you for being here! The GSF is a consortium of organizations across industries working collaboratively to build a trusted ecosystem of people, standards, tooling and best practices for green software. 

Green Software is software that is carbon-aware, hardware-efficient, and energy-efficient.
Collectively, our members represent the software industry and its commitment to decarbonization and software sustainability. If you're interested in learning more or would like your organization to become a member, visit greensoftware.foundation.  

Today, we're all here to delve into the intricate relationship between responsible AI and environmental sustainability. We wholeheartedly acknowledge that AI possesses the transformative potential to tackle some of our planet's most pressing global challenges, yet it also carries an environmental toll that can be detrimental to the health of our planet and societies.

Our mission is to guide AI towards a greener future where sustainability and innovation go hand in hand. Before we jump in, let's preview what our expert panel will explore:

- The current state of green software and its future
- Eco-friendly AI design and development principles
- Tools to measure AI's carbon footprint
- The roles of policy-makers, AI Sustainability Officers, and more
- How individuals and groups can drive change

Now, let's meet our panel:

Moderating today's discussion is Dawn Nafus, Anthropologist and Senior Research Scientist at Intel Labs, an expert in health, environmental sensing, and data.

Joining us, we have Chris McClean, Global Lead for Digital Ethics at Avanade, Navveen Balani, Chief Technologist at the Technology Sustainability Innovation Group at Accenture, and Dr. Elif Kiesow Cortez, Director of Quantum & AI at Ethiqual and Research Fellow on Tech Ethics & Governance at Stanford Law School.

We invite you to actively participate by asking questions, sharing your insights, and recounting your experiences. We're monitoring GSF Discussions (link in chat), LinkedIn and Twitter and YouTube, so keep your comments and questions coming! 

Alright, let's get started. Dawn, the mic is yours!
