### ISSUE TITLE
Policy Tracker

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#48]
## Policy Tracker

**What is it:** Creating a policy tracker to keep an eye on upcoming legislation and consultations where it would be beneficial for the GSF to see on the horizon, and respond to - either with coming policy briefs or formal responses to consultations from policy makers. This is somewhat inspired by [the policy compass used by EnergyTag in their own working groups](https://docs.google.com/spreadsheets/d/10uZ42Cw0-a6fGRuLKBNsi0zo77F-G1Tf-Cj5Nf2WqSY/edit#gid=0), as a way to coordinate responses ahead of time.

**The goal:** Understanding what considerations we have to bear in mind to support participation from members and finding a small subgroup to make a first draft.

**Comment by NAMRATA-WOKE** [comment]
@seanmcilroy29 I'm building this into the policy manual project I proposed and have included in the roadmap activities sheet: https://docs.google.com/spreadsheets/d/1ODRBf2a6OAYFJFYha1gZXrweQgE7LmqX6u7vZVMZJgo/edit#gid=0
