### ISSUE TITLE
GHG Protocol Working group - call for Technical Working Group members

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/policy-wg#61]
Dear policy working group members

Last year, we responded to a GHG Protocol consultation, about reforming how they measure carbon. There’s a new call, linked below, but I’ve included the a snippet that might be of interest:

https://ghgprotocol.org/blog/announcement-ghg-protocol-launches-call-expression-interest-technical-working-group

> Under the new structure, organizational governance will now be overseen by a Steering Committee, which will provide strategic guidance on the goals and direction of the GHG Protocol. This body will approve GHG Protocol’s mission, vision, strategy, and rules of procedure, appoint members to the Independent Standards Board, provide oversight of the Independent Standards Board and ratify its decisions.  The GHG Protocol Secretariat will continue to be hosted by World Resources Institute (WRI) and World Business Center for Sustainable Development (WBCSD). 
>
> The new Independent Standards Board, made up of leading global experts will oversee the standards development process, and ultimately approve final standards and guidance.
>
> Under the oversight of the Independent Standards Board, the Technical Working Groups will be convened on specific topics to develop the technical content of the standards. These groups will play a primary role in the development of the technical content of the updated GHG Protocol standards and guidance.  
>
> Once the GHG Protocol update process commences there will also be opportunities to participate in Review Groups. The Review Groups, open to all stakeholders, will provide feedback on draft standards. Pilot Testing Groups may also be convened as needed.  

When I shared this in the mailing list, there was interest from at least one other member to submit an application. We would need to nominate a policy working group member, and put them forward, in line with the application process below.

https://ghgprotocol.org/nominations-governance-bodies

**Comment by muemich** [comment]
Interested

**Comment by mrchrisadams** [comment]
Thanks @muemich  - I'm going to tag @NAMRATA-WOKE, following on the discussion during the call. Ideally we'd have time to share back in January about this, and an application from the GSF

**Comment by muemich** [comment]
We decided in the WG meeting on the 8th of Jan that it would be best if Asim submits and then channels work etc. into the WG.

**Comment by jawache** [comment]
Hey, @mrchrisadams and @muemich, I looked through this, and it does look like whoever you nominate will have to spend time representing your concerns in calls/meetings and then passing information back; there even looks like one in-person meeting a year. I suspect one of you would do a much better job of representing your issues than me.

I'm happy to submit my name for nomination, but I may be unable to make most of the calls or be a good channeller. However, as Chairs of a Working Group, you **can** represent the GSF in forums like this. We sometimes ask chairs to represent GSF in a call or panel or the like. As a Chair, you can go to places wearing the GSF hat and represent the GSF, like how @mrchrisadams represented the GSF at COP the year before last.

**Comment by muemich** [comment]
Ok! I'll submit and see what happens. Let's cross fingers that this works out.

**Comment by mrchrisadams** [comment]
Quick update - the deadline for this was extended to Jan 31st.

**Comment by seanmcilroy29** [comment]
Task completed
