### ISSUE TITLE
2024 01 22 - Responsible Computing

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#65]
# 2024 01 22

Time 0830 PST / 1630 BST - See the time in your timezone https://everytimezone.com/s/a8399b00

- Chair – Chris Adams (The Green Web Foundation)
- Chair - Lisa McNally (Thoughtworks)
- Chair - Michael Mueller (Re-cinq)
- Convener –  Sean Mcilroy (Linux Foundation)

## Antitrust Policy

Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings

The Working Group Meeting is [recorded](https://docs.google.com/document/d/1ttKxQE6GweNAI1TCfIq-Fgbv6WIEIuDRbLnIP1ZJ5N8/edit) and is available for members to review until the next scheduled meeting.

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, GitHub username (optional)
 
## MoU - Responsible Computing
- [ ] [SustainableIT](https://docs.google.com/document/d/12kyPKBFZAsseF1ATWr9OJ6hDUDCCkiyg/edit) MoU draft.

> Since we last spoke, Responsible Computing had a few changes of strategy and funding and is mow working on updating their roadmap, before deciding where best to collaborate with groups like the Green Software Foundation. We agreed to pick this up at a later date, following a separate discussion between Michael (Responsible Computing) and Lisa (GSF PWG)

### Reviewing draft policy - AI Environmental Impacts Act

> Earlier this week staff representing US Markey contacted the GSF to ask for input on draft legislation on the environmental impact of AI. This draft legislation has been shared for review and to discuss at the next meeting.

## Upcoming Events

> deferred to the next meeting 

- [ ] [Carbon Hack 2024](https://docs.google.com/presentation/d/13IqItz50G3jrsjOlyt4vZtSejUW29TEe/edit#slide=id.g29f073d87a6_1_34)

## Next meeting 
- [x] ~~05th Feb 2024~~ 29th Jan

> The extra-ordinary meeting with Responsible Computing meant that in order to respond to a existing reviews from both [the Carbon Trust Decarbonising the Use-Phase of Connected Devices](https://github.com/Green-Software-Foundation/policy-wg/issues/67) and the AI Environmental Impacts Act mentioned above, the next meeting was brought forward to Jan 29th.

## Adjourn 
- [x] Motion to adjourn
--------

## Previous Meeting Action Items
- [ ] Nothing outstanding

**Comment by muemich** [comment]
attended

**Comment by mrchrisadams** [comment]
Attended

**Comment by lisamcnally** [comment]
Attended

**Comment by smol84** [comment]
Attended

**Comment by kapokasa** [comment]
attended

**Comment by lisamcnally** [comment]
attended
