### ISSUE TITLE
2024 02 05

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/policy-wg#66]
# 2024 02 05

Time 0830 PST / 1630 BST - See the time in your timezone https://everytimezone.com/s/a8399b00

- Chair – Chris Adams (The Green Web Foundation)
- Chair - Lisa.McNally (Thoughtworks)
- Chair - Michael Mueller (Re-cinq)
- Convener –  Sean Mcilroy (Linux Foundation)

## Antitrust Policy

Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings

The Working Group Meeting is [recorded](https://docs.google.com/document/d/1ttKxQE6GweNAI1TCfIq-Fgbv6WIEIuDRbLnIP1ZJ5N8/edit) and is available for members to review until the next scheduled meeting.

### Roll Call 
Please *add 'Attended'* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, GitHub username (optional)

## Agenda
- [x] Approve Agenda / previous minutes #65   

## Breaking the Policy WG roadmap down
- [x] [Review spreadsheet](https://docs.google.com/spreadsheets/d/1ODRBf2a6OAYFJFYha1gZXrweQgE7LmqX6u7vZVMZJgo/edit#gid=0)

## Partner Review - Decarbonising the Use-Phase of Connected Devices
-  [ ] Delegate the review to a sub-group to share feedback with the Carbon Trust
See the [thread in the policy wg mailing list](https://groups.google.com/a/greensoftware.foundation/g/policy-wg/c/fDJZK3k0PLA)

- [Link to Google Drive folder](https://drive.google.com/drive/folders/11nyVsVhcQMOE8RR5nsjS4XcE8jXwMTEm)

## AI Environmental Impact Act of 2024 Review - Chris
- See [the thread in the policy wg mailing list](https://groups.google.com/a/greensoftware.foundation/g/policy-wg/c/In8rvj0NrEM)
- link [to Google Drive folder](https://drive.google.com/drive/folders/1zAiQiZqXHZFGMasyT9Rwu_g9i4C7BFG2)
> SC agree to endorse the proposed legislation

## Round Table Proposal - Sean
Discussions with fellow foundations to understand their primary focused areas.
- OS Climate
- Finos
- LFEnergy
- CNCF

## Any other business

- [ ] Discuss the process that the GSF should follow to allow for recommendation of legislation and review and approval by the Steering Committee (documenting on GitHub for transparency and reference; Sean will add an issue and Namrata will send follow-up email to Ollie once that is completed)
- [ ] Share next steps for finalizing the SustainableIT MOU now that they have approved the final version
- [ ] Discuss next steps, if any, for follow up with Michael L. at Responsible Computing
- [ ] Co-chair facilitator for 2/19 meeting is Michael M.
 
## Next meeting 

- [ ] 19th Feb 2024

## Adjourn 
- [ ] Motion to adjourn
--------

## Previous Meeting Action Items

- [ ] Update about the financial round table
- [ ] Finding time to discuss COP / UN engagement (UN's Green Digital Action inquire if interested in participating in GSF round table)

**Comment by mrchrisadams** [comment]
Attended

**Comment by mcrubellati** [comment]
attended

**Comment by seanmcilroy29** [comment]
Attended

**Comment by lisamcnally** [comment]
Attended

**Comment by seanmcilroy29** [comment]
Meeting opened by Lisa @ 1630 GMT

**MoM**

**AI policy and environmental impact.** 
Lisa McNally facilitates a policy working group meeting, discussing updates to the Antitrust Policy and the environmental impacts of AI.

Participants review and approve previous meeting minutes with no objections.

Lisa McNally and Namrata discuss the policy working group's roadmap, with Lisa highlighting the group's three major initiatives and Narada adding colorful details.

The group plans to inform their membership and communicate with other working groups to identify potential synergies and collaborations. Lisa mentions a policy Working Group roadmap to organise activities and communicate with members.
Chris proposes a subtask group to gather feedback on AI environmental legislation with a partner review period today.

**Carbon footprint specs and standards.** 
Chris reviews a 57-page spec document, which he will share with the group. He plans to discuss the feedback via a synchronous video call with the group. Chris mentions a partner opportunity for the specification draft, with partner calls coming up in the next few weeks. Lisa suggests reaching out to standards groups for potential overlap with the green rating, and Chris agrees to circulate feedback and book time for a discussion.

**AI environmental impact and policy.**
Lisa seeks clarity on AI environmental submission. Lisa suggests documenting the SC's approval process for policy-related issues. Chris shares his recollection of the drafts shared with the group, with only one response from a member. Chris explains the process of recommending to the SC, including the approach used in other working groups.

Documenting the decision-making process for a project.
Lisa and Namrata discuss the decision made during a previous meeting regarding a task, with Lisa expressing the need to document the decision before sending an email to Ollie. The two agreed to wait until Monday's discussion with Radha before emailing Ollie to ensure they have covered all necessary steps and best practices.

**Documenting SC decisions and sending emails to Ollie.** 
The SC members generally are not responding to emails, making it difficult to get approvals and move forward with decisions. Having an R&A allows SC members to have the opportunity to object/agree on new legislation within a set timeline to avoid delays. Lisa suggests documenting SC approvals on GitHub for transparency and accountability. Sean agrees and proposes bringing it up at the next SC meeting. Lisa seeks approval to email Ollie regarding the SC endorsement for the legislation.

**Collaboration among groups working on sustainable energy solutions.** 
Sean seeks to bring together four groups working on sustainability efforts at LF Energy to collaborate and avoid duplication of effort. Lisa suggests a SC to oversee the various organisations' initiatives, with co-ownership from a representative from each organisation. Sean agrees, noting that leveraging resources and citing each other's work in papers can be beneficial.
Sean and Lisa discuss the Linux Foundation's five foundations, including FinOps and Fin OS, and how they are aligned with each other and the SCI standard. Sean mentions that Fin Ops is not aligned with their goals, but Fin OS is, and they plan to discuss it with the Fin Ops foundation.

**Policy manual** 
Lisa suggests creating a policy manual and seeking input from the policy working group.
The group discusses the process for creating the manual and decides to table the decision until the next meeting.

Meeting closed 17:30

**Comment by mrchrisadams** [comment]
I've created the discussion in the standards wg for feedback.  I have a call booked on Feb 23rd to talk with the Carbon Trust about the end user use phase emissions decarbonisation spec.

see below for my notification of the standards wg

https://github.com/Green-Software-Foundation/standards-wg/discussions/101

**Comment by lisamcnally** [comment]
Thanks so much, Chris!-LisaOn Feb 9, 2024, at 12:07 AM, Chris Adams ***@***.***> wrote:﻿
I've created the discussion in the standards wg for feedback.  I have a call booked on Feb 23rd to talk with the Carbon Trust about the end user use phase emissions decarbonisation spec.
see below for my notification of the standards wg
Green-Software-Foundation/standards-wg#101
