### ISSUE TITLE
[PRESS RELEASE] SustainableIT.org Partnership

### ISSUE THREAD

**Issue by NAMRATA-WOKE** [Green-Software-Foundation/policy-wg#68]
Article Details
Please enter the details here

Proposer: Namrata Narayan | Dir. Comms & Member Relations | @NAMRATA-WOKE
Timeline: Likely January/February 2024

Important Information
To be filled out later

Author: @NAMRATA-WOKE
Other contributors: PWG co-chairs
[MoU Link](https://docs.google.com/document/d/1aOrK7GS75YqZ9I3menpF2hMTE89_Flw1r1Pl5JT5_Oc/edit)
[PR Link](https://docs.google.com/document/d/1DhesGlQaqZtiYe0_697LajvH3lwGux8h3gfUflbCfcE/edit?usp=sharing)
Graphics Link: (Link to the design assets for this article, must be in our official GSF drive)
Published Link: (The link the article was published to for memory)

Checklist

- [x]  Idea discussed and selected for writing. After checking this box, set Status to "Todo" under "Articles" project
- [x]  Author identified. After checking this box Assign issue to the Author
- [x]  Scheduled in calendar
- [x]  Google doc link created in GSF drive.
- [x]  In progress. After checking this box, set Status to "In Progress" under "Articles" project
- [x]  Draft created. After checking this box, set Status to "In Review" under "Articles" project. Assign issue to Reviewer/Author during the back-and-forth
- [x]  Draft reviewed. After checking this box, set Status to "In Publishing" under "Articles" project. Assign issue to Graphic Designer and add "Graphic Design" to issue's Projects
- [x]  Graphics created. After checking this box, assign to TBC for approval.
- [x]  Approved. After checking this box, assign to TBC for publishing.
- [x]  Published. After checking this box, set Status to "Ready" under "Articles" project. Assign to Marketing and add "D: Marketing" to issue's Projects
- [x]  Shared on socials
- [x]  Shared on newsletter. After checking this box, set Status to "Done" under "Articles" project and close issue.

**Comment by NAMRATA-WOKE** [comment]
@jawache since Lisa McNally is a co-founder and lead the MoU, is it okay to have the GSF quote be from her, or do you prefer its from you? I wasn't sure since we typically don't mention the names of volunteers in our communications. If we are okay with it for PRs of this kind (strategic partnerships), then I'll ensure the PWG signs off! :) 

Can't wait for the Comms Committee to materialize to take some of this decision-making off our plate!

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please allow me the access to the draft if it's ready for graphic design

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the update attached and [on Drive](https://drive.google.com/drive/folders/1IUZ_pmBnUXUMTj03ZAdbTWpsGGte7KD6?usp=drive_link)
Sorry, it looks like I missed my deadline for this task, for some reason I paid attention on the checklist, not on the date, my bad.

![Image](https://github.com/Green-Software-Foundation/policy-wg/assets/69306070/d2b20780-b79e-4400-83dc-f739959626ba)

**Comment by russelltrow** [comment]
* Sanjay needs to sign agreement
* Awaiting a review from Sustainable IT

**Comment by NAMRATA-WOKE** [comment]
Sanjay has signed the agreement and Lisa has shared it with the new lead at SustainableIT for their signature!

**Comment by russelltrow** [comment]
@seanmcilroy29 to update issue with details to move forward

**Comment by seanmcilroy29** [comment]
@NAMRATA-WOKE - The MoU has been fully executed.
SustainableIT Contact - Josh Harbert (President ) Josh.Harbert@sustainableit.org

**Comment by seanmcilroy29** [comment]
PR for your review - https://docs.google.com/document/d/1DhesGlQaqZtiYe0_697LajvH3lwGux8h3gfUflbCfcE/edit
