### ISSUE TITLE
[AI] NSF collaboration

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/policy-wg#75]
### NSF potential collaboration

**Broader Impacts:** This project will provide insight into the historical, social, and technical aspects of AI's environmental footprint. As pending AI regulation calls for participatory methods and inputs from marginalized communities, this research provides a model that can be adapted to multiple types of assessments and will foster relationship building between industry and marginalized communities to build trust in development and deployment decisions. 

- [AI Environmental Impacts_ReDDDoT Partner Letter Template.docx](https://github.com/Green-Software-Foundation/policy-wg/files/14930502/AI.Environmental.Impacts_ReDDDoT.Partner.Letter.Template.docx)
- [NSF Summary.pdf](https://github.com/Green-Software-Foundation/policy-wg/files/14930503/NSF.Summary.pdf)

**Comment by seanmcilroy29** [comment]
**Review and Approval Period**
The PWG has requested that a review period be initiated until April 19th, during which members can submit any objections or comments. If no comments are submitted, the proposal will be approved on the 19th Apr
- Open: 16 Apr
- Closes: 19 Apr

**Comment by NAMRATA-WOKE** [comment]
@seanmcilroy29 have we received any objections?

**Comment by lisamcnally** [comment]
@seanmcilroy29 Checking in, since I think the SC meeting was earlier today. Did we receive Sanjay's signature on the Letter of Intent? If so, could you please forward the signed letter (link or attachement) so I can get it to Tamara? She need to attach to her proposal by Monday. Thank you!
